const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const core = require('@actions/core');

async function run() {
  try {
    const top = core.getInput('top') || '10';
    const since = core.getInput('since') || '';
    const failScore = parseInt(core.getInput('fail-on-curse-score') || '0', 10);
    const repoPath = process.env.GITHUB_WORKSPACE || '.';

    core.info('⛏ Running Git Archaeologist...');

    // Build command using npx — no global install needed
    let cmd = `npx git-archaeologist@latest analyze ${repoPath} --json`;
    if (since) cmd += ` --since ${since}`;

    const output = execSync(cmd, { maxBuffer: 50 * 1024 * 1024 }).toString();
    const result = JSON.parse(output);

    const cursed = result.cursedFiles || [];
    const topFile = cursed[0];

    if (topFile) {
      core.setOutput('top-cursed-file', topFile.filepath);
      core.setOutput('top-curse-score', String(topFile.curseScore));
    }

    // Build summary
    const sinceLabel = since ? ` (since ${since})` : '';
    let summary = `## ⛏ Git Archaeologist Report${sinceLabel}\n\n`;
    summary += `**${result.totalCommits} commits · ${result.totalFiles} files · ${result.totalAuthors} authors**\n\n`;

    if (cursed.length > 0) {
      summary += `### 💀 Top ${Math.min(parseInt(top), cursed.length)} Cursed Files\n\n`;
      summary += `| Rank | File | Score | Changes | Authors | Why |\n`;
      summary += `|------|------|-------|---------|---------|-----|\n`;
      cursed.slice(0, parseInt(top)).forEach((f, i) => {
        summary += `| ${i+1} | \`${f.filepath}\` | **${f.curseScore.toFixed(0)}** | ${f.totalChanges} | ${f.uniqueAuthors} | ${(f.reasons || []).join(', ')} |\n`;
      });
    }

    const busFactor1 = (result.busFactor || []).filter(b => b.busFactor === 1);
    if (busFactor1.length > 0) {
      summary += `\n### 🚌 Bus Factor 1 Modules (single point of failure)\n\n`;
      busFactor1.forEach(b => {
        summary += `- **${b.scope}** — ${b.atRiskAuthors[0]}\n`;
      });
    }

    summary += `\n---\n*Generated by [git-archaeologist](https://github.com/SushantVerma7969/git-archaeologist)*\n`;

    await core.summary.addRaw(summary).write();
    core.info(summary);

    if (failScore > 0 && topFile && topFile.curseScore >= failScore) {
      core.setFailed(`🚨 Curse score threshold exceeded: ${topFile.filepath} scored ${topFile.curseScore.toFixed(0)} (threshold: ${failScore})`);
    }

  } catch (err) {
    core.setFailed(err.message);
  }
}

run();
